### ISSUE TITLE
Tweak Red Interior demo scene and update included render

### ISSUE THREAD

**Issue by nyers33** [appleseedhq/blenderseed#197]
The rendered image of the red interior demo scene [right] differs from the sample picture [left] that comes with the scene file.
![blenderseed_red_interior_demo_scene_1 2](https://user-images.githubusercontent.com/37452404/37535624-92ae5dd8-2948-11e8-9265-ec1bde5ff526.jpg)
Blender: 2.79
appleseed: 1.8.1-beta-0-gb3b5172-win64-vs140
blenderseed: 0.7.1
red_interior_demo_scene: 1.2

**Comment by dictoon** [comment]
We're looking into it.

**Comment by jdent02** [comment]
So first thing is that I don't believe the filmic view was used on the original picture.  The 0.7 version of the file does have filmic enabled, so that changes the contrast quite a bit.  As far as the color it largely appears to be due to the lighting being a bit colder and brighter in the 0.7 file.  If I remember right Luke completely redid this scene after it broke with some of the material redos.  Something might have been changed and I think the demo picture was rendered with the original version of the file.

**Comment by nyers33** [comment]
Thx for the clarification!

**Comment by dictoon** [comment]
Thanks @jdent02! We should probably tweak the scene (the lighting in the older scene was definitely nicer) and also update the included render. Updating the issue's title.

**Comment by jdent02** [comment]
I'm gonna take on this one.

**Comment by jdent02** [comment]
I'm not sure if this one is salvageable.  Maybe we should come up with a new demo scene using the 2.8 exporter?

**Comment by dictoon** [comment]
Yes, that would be great.

**Comment by jdent02** [comment]
Closing.  Will be creating a new demo scene
