### ISSUE TITLE
Minor adjustments

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#210]
- Minimum filter size should be 0.5, not 0.0.
- Exported projects have Max Diffuse Bounce set to 0 for the interactive configuration, that doesn't match what's set in blenderseed.

**Comment by dictoon** [comment]
Also, some error messages appear in the system console:

```
ui\render.py:163
rna_uiItemR: property not found: AppleseedRenderSettings.sampler_max_variation

ui\render.py:164
rna_uiItemR: property not found: AppleseedRenderSettings.sampler_max_contrast

TypeError: EnumProperty(..., default='sRGB'): not found in enum members
```

**Comment by jdent02** [comment]
TypeError: EnumProperty(..., default='sRGB'): not found in enum members 

is due to another typo in the OSL file.  in_y_tex_eotf is a string yet it uses the (name):(integer) formatting for the options.  That's not needed (the integers are not used anywhere) and it screws up the blenderseed parser.

I've had to fix a couple of these typos lately.

**Comment by jdent02** [comment]
sampler_max_variation and sampler_max_contrast are in the render_ui.py module.  The actual variables do not exist in either the scene.py file or the projectwriter.py file so I'm assuming they aren't used anymore and we just forgot to remove them from the UI

**Comment by dictoon** [comment]
I'm closing this since it appears to be done. Please reopen if necessary.
