### ISSUE TITLE
Recent changes to asMetal node inputs are incompatible with older scenes

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/blenderseed#355]
My guess is the recent elimination of the energy compensation input in asMetal.osl leads to an `unidentified socket type`error when older scenes are loaded and prevents material preview and production rendering. Replacing the old asMetal node in the Node Editor with a new one fixes rendering.

![node_error](https://user-images.githubusercontent.com/22252558/48675677-8a0a7c00-eb64-11e8-8276-f53dc21ffd7a.PNG)

**Comment by jdent02** [comment]
So is this a blenderseed issue or an appleseed one?  Seems the latter.....

**Comment by Mango-3** [comment]
Well it is not strictly a blenderseed issue, more an  OSL-shader issue, but one which is tied to the DCC-specific plugin.
How (unused) inputs are exposed depends on the platform specific metadata. In appleseed-Max we don't have this problem because the `Energy Compensation` input was never exposed to the user, only internally set to `fully compensated`. In appleseed-Maya the input was also hidden from the user as far as I know.

**Comment by luisbarrancos** [comment]
Ok, so the problem was that this parameter was inadvertantly exposed to the user in blenderseed, and the addition of the input_socket = 0 metadata token, that disallows any input connections to this slot, is breaking scenes that actually had input connections to this socket.
The only solution is keep the parameter hidden as it is now, but comment out the blender metadata. token, input_socket. This was not exposed nor used in other DCC plugins.

**Comment by jdent02** [comment]
Hi Luis. Just the fact that the connection was exposed is causing the error, it has nothing to do with whether it was hooked up or not

**Comment by jdent02** [comment]
#388 fixes this

**Comment by dictoon** [comment]
> #388 fixes this

Does it? I thought it also introduced other backward-compatibility breaking changes.
