### ISSUE TITLE
Max Ray Intensity for SPPM should default to Unlimited, not 1

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#384]

**Comment by leonard7e** [comment]
I like to get my feet wet. 

https://github.com/leonard7e/blenderseed/commit/a3e1e3bd37abea5efa2c339717b1935563710264

**Comment by jdent02** [comment]
I think unlimited is actually -1

**Comment by dictoon** [comment]
Whether Max Ray Intensity (MRI) is enabled or not is based on the presence or absence of the corresponding parameter. In the case of SPPM's Path Tracing step, the exact parameter name is `path_tracing_max_ray_intensity`. As soon as this parameter is present, MRI is enabled, regardless of its value (0, -1, infinity).

**Comment by leonard7e** [comment]
Disabling path_tracing_max_ray_intensity entirely and set this property to -1 
would have same similar visual effect?

https://github.com/leonard7e/blenderseed/commit/d5f2ae95e1dc2ba85bd2632673deea1692174575
sppm_pt_max_ray_intensity_unlimited

Whole branch only for communication, maybe there is a better way exchanging ideas? It is my very beginning colab with others on Github. 
I am sorry about indentation misstake. Fixed in next commit. 

Need to afk soon. Till evening.

**Comment by dictoon** [comment]
It's best to discuss in your PR.

**Comment by jdent02** [comment]
#415
