### ISSUE TITLE
GLIBC_2.25 not found

### ISSUE THREAD

**Issue by KMean** [appleseedhq/blenderseed#411]
when enabling the blenderseed plugin I got this:

```
[kim@linux blender]$ ./blender
found bundled python: /home/kim/Applications/blender/2.79/python
Exception in module register(): '/home/kim/.config/blender/2.79/scripts/addons/blenderseed/__init__.py'
Traceback (most recent call last):
  File "/home/kim/.config/blender/2.79/scripts/addons/blenderseed/appleseed/lib/appleseed/__init__.py", line 35, in <module>
    from _appleseedpythonbuiltin import *
ImportError: No module named '_appleseedpythonbuiltin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kim/Applications/blender/2.79/scripts/modules/addon_utils.py", line 350, in enable
    mod.register()
  File "/home/kim/.config/blender/2.79/scripts/addons/blenderseed/__init__.py", line 64, in register
    from . import export
  File "/home/kim/.config/blender/2.79/scripts/addons/blenderseed/export.py", line 33, in <module>
    from .translators import SceneTranslator
  File "/home/kim/.config/blender/2.79/scripts/addons/blenderseed/translators/__init__.py", line 29, in <module>
    from .scene import SceneTranslator
  File "/home/kim/.config/blender/2.79/scripts/addons/blenderseed/translators/scene.py", line 33, in <module>
    import appleseed as asr
  File "/home/kim/.config/blender/2.79/scripts/addons/blenderseed/appleseed/lib/appleseed/__init__.py", line 45, in <module>
    from ._appleseedpython3 import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/kim/.config/blender/2.79/scripts/addons/blenderseed/appleseed/lib/appleseed/_appleseedpython3.so)
```

this is happening also when launching the application:

```
[kim@linux bin]$ ./appleseed.studio
./appleseed.studio: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./appleseed.studio)
./appleseed.studio: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/kim/Applications/appleseed/bin/../lib/libappleseed.so)
./appleseed.studio: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/kim/Applications/appleseed/bin/../lib/libexpat.so.1)
```

Any Ideas? I'm running a fresh install of Centos7

**Comment by Mango-3** [comment]
Hi KMean,

The problem is that CentOS uses an old version of glibc (2.17) which is not compatible with the blenderseed binary. Also, Blender 2.8 won't run on CentOS due to the same [issue](https://devtalk.blender.org/t/unable-to-run-blender-2-80-in-rhel-centos-7/2138/45) 
Unfortunately there is no good solution. You would need to compile appleseed and its dependencies on your machine from source. The prebuild appleseed dependencies for Linux use a newer glibc version, so they wont be usable. 
Then you would need to build a statically linked blenderseed compiled against your appleseed which is really difficult.  
We are working on a new binary build of current blenderseed for Linux which should be able to run with CentOS but this will take a bit of time. 

CentOS 8, which is due in summer, will use newer compiler and glibc versions and then this problem will be solved without workarounds.

**Comment by jdent02** [comment]
Can this one be considered solved?

**Comment by Mango-3** [comment]
I think so. There is nothing to change from blenderseed's side. 
Esteban is aware of this problem and tries to get new dependencies and a new static build ready.

**Comment by KMean** [comment]
Thanks for the reply... I’ll wait for next centos release.

Kim Ranzani
