### ISSUE TITLE
3D Quad view – Blenderseed 1.0.0 interactive render crashes 

### ISSUE THREAD

**Issue by leonard7e** [appleseedhq/blenderseed#419]
Blenderseed 1.0.0
Blender 2.79b

Quad view crashes interactive rendering.

Activate quad view:
(1) Inside 3D-Editor: Strg+Alt+q 
(2) (3D-Editor menu) / view / Toggle Quad View

After you have quad view, start interactive rendering.

I could not try newer versions of Blenderseed. Does this problem still persist in the more recent Blenderseed / Blender 2.80?

Regards,
Leonard

**Comment by jdent02** [comment]
I’ll have to take a look at it. Not sure how Blender handles the four cameras or displaying the results when it comes to interactive rendering.

Sent from my iPhone

On May 13, 2019, at 1:00 PM, Leonard Siebeneicher <notifications@github.com<mailto:notifications@github.com>> wrote:


Blenderseed 1.0.0
Blender 2.79b

Quad view crashes interactive rendering.

Activate quad view:
(1) Inside 3D-Editor: Strg+Alt+q
(2) (3D-Editor menu) / view / Toggle Quad View

After you have quad view, start interactive rendering.

I could not try newer versions of Blenderseed. Does this problem still persist in the more recent Blenderseed / Blender 2.80?

Regards,
Leonard

**Comment by jdent02** [comment]
So I have good news and bad news for this one:

Bad news is I'm not sure what's causing it to bork up in 2.79.  I can see what the problem is but I don';t know why it's occurring or how to fix it.  What's happening is Blender is creating 4 different render engine instances (one for each panel) but then it's immediately destroying them,  Then on the next app tick it does the same thing.  I kept a running count and over about two seconds there were over 200 render engine instances created and destroyed.  Cycles creates 4 instances one time and then keeps them running properly.  I honestly don't know why that is happening.

Good news is that interactive quad view works just fine in 2.8.

**Comment by leonard7e** [comment]
Still good news.
Blender 2.80 on the road, maybe on July.

**Comment by jdent02** [comment]
Knowing the Institute I'd expect it in August or even September.

We're still determining if the next official blenderseed will be under 2.79b or 2.8.

**Comment by jdent02** [comment]
I'm going to keep this issue open until 2.8 so other people will know that it's a known problem.

**Comment by leonard7e** [comment]
If I have a vote, I would vote (to wait) for Blender 2.80.

Imo, it would be a pity, if Blenderseed is released for Blender 2.79b, when most people already move away to 2.80. 

But it is good to know, that this problem does not persist for 2.80 any more.

Happy creating.

**Comment by jdent02** [comment]
The 2.79 branch will have at least one more official release I would imagine.  Whether that is on it's own or combined with the 2.8 release we'll have to see how the timing pans out.  While pretty much all my time is spent in 2.8 now, I don't think it would be a good idea to ditch the 2.79 exporter quite yet.  Some people are going to take time to migrate to 2.8
