### ISSUE TITLE
Ignore OSL shaders that don't have the right attributes

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#445]
I have an `APPLESEED_SEARCHPATH` environment variable on my system that points to appleseed's shader directories. That caused blenderseed to find 3ds Max shaders (among others) and it crashed because the `as_max_color_texture` shader has a parameter `U` of type `float that hasn't got a `default` attribute:

![image](https://user-images.githubusercontent.com/321290/64288372-3a196c00-cf62-11e9-868d-fab286279914.png)

Temporarily removing the `APPLESEED_SEARCHPATH` environment variable fixed the problem but it would be nice not to have to do that.

**Comment by jdent02** [comment]
This fix isn't quite as easy as it seems.  The addon can't make any assumptions about what's in APPLESEED_SEARCHPATH since there's no certainty that it's organized in a particular way (like the appleseed shader directory).  I suppose anything containing the terms '3DSMax' or 'Maya' could be excluded but that might remove perfectly usable OSL shaders that just have those words in their filepaths.  I think in this case we just have to trust the user to point that env variable at the right place.

**Comment by dictoon** [comment]
What I meant is that instead of chocking or crashing when encountering a shader that blenderseed can't handle, it should simply mention that in the log and skip it.

**Comment by dictoon** [comment]
We need to fix this problem and never crash, regardless of how incompatible OSL shaders encountered in the search paths are. Problematic shaders must be ignored but shader discovery must proceed without crashing.

**Comment by dictoon** [comment]
Bumping this up, this one is a major issue for me.

**Comment by dictoon** [comment]
> So, after looking at this a bit more I can't just ignore shaders that don't have defaults for some variables.

Why not?

My point is simply that blenderseed should survive and continue to work fine even if the user throws random, non-compliant OSL shaders in his search paths.

**Comment by dictoon** [comment]
One way to achieve this would be to wrap the shader discovery/parsing code in a giant try-catch all block and simply skip any shader that causes an exception to be thrown.
