### ISSUE TITLE
Clipping planes?

### ISSUE THREAD

**Issue by adenirantayo** [appleseedhq/blenderseed#490]
In blenderseed, clip parameter under camera is not working.

**Comment by jdent02** [comment]
Near or far clip?  appleseed cameras have no far clip parameter.

**Comment by adenirantayo** [comment]
Okay. Will it be implemented soon?

**Comment by dictoon** [comment]
It would be easy to implement. Can you elaborate on the use case please?

**Comment by adenirantayo** [comment]
I would like to use it for 3d archviz, sometimes, I need the camera to see past 3d building walls, instead of moving the camera inside of the 3d building

**Comment by dictoon** [comment]
Wouldn't you need a near clip plane to skip walls in front of the camera?

**Comment by adenirantayo** [comment]
Would the near clip plane serve that purpose? Forgive my knowledge of this, I'm using cycles as reference to explain. In Cycles, it is called Clip start, underneath Clipping

**Comment by dictoon** [comment]
Start from the camera and move toward the scene. The first clipping plane you encounter is the **near plane**: everything _before_ that plane (i.e. everything between the camera and the near plane) is ignored. The next clipping plane you encounter is the **far plane**: everything _after_ that plane is ignored.

Given the effect you describe, I believe that Cycles' "clip start" is what we call a near plane in appleseed. As it turns out, the near plane is supported in appleseed. In the current version of appleseed it must be negative (the more negative, the farther the near clip plane is from the camera).

**Comment by adenirantayo** [comment]
Thank you very much
